In [4]:
import numpy as np
import cv2
import os
import time

In [2]:
hand_sign_images = []
target = []
sign_and_numbers = {}
sign_no = 0


In [3]:
source = cv2.VideoCapture(0)
for i in range(5):
    image_no = 0
    sign = input("Please enter the sign : ")
    print("Starting in 5 seconds...")
    time.sleep(5)
    while 1:
        not_to_use, image = source.read()
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        x = 30
        y = 30
        w = 350
        h = 350
        hand_roi = gray[y:y+w, x:x+h]
        resized_image = cv2.resize(hand_roi, (100, 100))
        #normalized_image = resized_image/255
        hand_sign_images.append(resized_image)
        target.append(sign_no)

        cv2.putText(image, "Image No : " + str(image_no), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (100, 100, 100), 2)
        image_no += 1
        cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
        cv2.imshow('Verzeo Project', image)
        cv2.imshow("Just Hand", hand_roi)
        key = cv2.waitKey(1)
        if image_no == 200:
            break
    
    
    sign_and_numbers[sign_no] = sign
    sign_no += 1
    cv2.destroyAllWindows()
source.release()

Please enter the sign : Hey
Starting in 5 seconds...
Please enter the sign : Okay
Starting in 5 seconds...
Please enter the sign : Best
Starting in 5 seconds...
Please enter the sign : Victory
Starting in 5 seconds...
Please enter the sign : Namaste
Starting in 5 seconds...


In [4]:
sign_and_numbers

{0: 'Hey', 1: 'Okay', 2: 'Best', 3: 'Victory', 4: 'You'}

In [5]:
len(hand_sign_images), len(target)

(2500, 2500)

In [6]:
hand_sign_images

[array([[ 2,  2,  2, ..., 11, 12, 12],
        [ 1,  2,  2, ..., 12, 12, 12],
        [ 1,  2,  1, ..., 12, 11, 12],
        ...,
        [ 1,  1,  1, ...,  1,  1,  1],
        [ 2,  1,  1, ...,  1,  1,  1],
        [ 1,  1,  1, ...,  1,  1,  1]], dtype=uint8),
 array([[ 52,  56,  56, ..., 102,  97, 100],
        [ 56,  51,  57, ...,  99, 101, 100],
        [ 58,  54,  53, ...,  98,  96,  99],
        ...,
        [ 36,  40,  44, ...,  28,  25,  30],
        [ 39,  38,  39, ...,  25,  26,  25],
        [ 35,  35,  36, ...,  26,  28,  29]], dtype=uint8),
 array([[ 55,  56,  55, ...,  99,  97, 101],
        [ 55,  57,  56, ..., 100,  98,  96],
        [ 53,  51,  51, ...,  96,  98,  98],
        ...,
        [ 76, 112, 145, ...,  27,  25,  30],
        [ 57,  97, 131, ...,  26,  24,  27],
        [ 48,  91, 119, ...,  28,  26,  29]], dtype=uint8),
 array([[ 55,  56,  55, ...,  99,  97, 101],
        [ 55,  57,  56, ..., 100,  98,  96],
        [ 53,  51,  51, ...,  96,  98,  98],
       

In [7]:
hand_sign_images = np.array(hand_sign_images)/255.0

In [8]:
hand_sign_images

array([[[0.00784314, 0.00784314, 0.00784314, ..., 0.04313725,
         0.04705882, 0.04705882],
        [0.00392157, 0.00784314, 0.00784314, ..., 0.04705882,
         0.04705882, 0.04705882],
        [0.00392157, 0.00784314, 0.00392157, ..., 0.04705882,
         0.04313725, 0.04705882],
        ...,
        [0.00392157, 0.00392157, 0.00392157, ..., 0.00392157,
         0.00392157, 0.00392157],
        [0.00784314, 0.00392157, 0.00392157, ..., 0.00392157,
         0.00392157, 0.00392157],
        [0.00392157, 0.00392157, 0.00392157, ..., 0.00392157,
         0.00392157, 0.00392157]],

       [[0.20392157, 0.21960784, 0.21960784, ..., 0.4       ,
         0.38039216, 0.39215686],
        [0.21960784, 0.2       , 0.22352941, ..., 0.38823529,
         0.39607843, 0.39215686],
        [0.22745098, 0.21176471, 0.20784314, ..., 0.38431373,
         0.37647059, 0.38823529],
        ...,
        [0.14117647, 0.15686275, 0.17254902, ..., 0.10980392,
         0.09803922, 0.11764706],
        [0.1

In [9]:
len(hand_sign_images[0])

100

In [10]:
hand_sign_images = np.resize(hand_sign_images, (2500, 100, 100, 1))
hand_sign_images

array([[[[0.00784314],
         [0.00784314],
         [0.00784314],
         ...,
         [0.04313725],
         [0.04705882],
         [0.04705882]],

        [[0.00392157],
         [0.00784314],
         [0.00784314],
         ...,
         [0.04705882],
         [0.04705882],
         [0.04705882]],

        [[0.00392157],
         [0.00784314],
         [0.00392157],
         ...,
         [0.04705882],
         [0.04313725],
         [0.04705882]],

        ...,

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00784314],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]]],


       [[[0.20392157],
         [0.21960784],
         [0.21

In [11]:
from keras.utils import np_utils
target = np_utils.to_categorical(target)
target

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(hand_sign_images, target)

In [14]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((1875, 100, 100, 1), (625, 100, 100, 1), (1875, 5), (625, 5))

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Activation, Dropout
from tensorflow.keraskeras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

In [2]:
model = Sequential()

NameError: name 'Sequential' is not defined

In [1]:
model.add(Conv2D(200, (3,3), input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(5, activation='softmax'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

NameError: name 'model' is not defined

In [18]:
cp = ModelCheckpoint('model-best2', verbose=0, save_best_only=True)
model.fit(X_train, Y_train, epochs = 3, callbacks=[cp], validation_split=0.2)

Epoch 1/3
47/47 [==============================] - ETA: 0s - loss: 0.7685 - accuracy: 0.6880WARNING:tensorflow:From E:\Applications\Anaconda\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: model-best2\assets
47/47 [==============================] - 75s 2s/step - loss: 0.7685 - accuracy: 0.6880 - val_loss: 0.2129 - val_accuracy: 0.9253
Epoch 2/3
47/47 [==============================] - 84s 2s/step - loss: 0.0889 - accuracy: 0.9760 - val_loss: 0.0289 - val_accuracy: 0.9947
Epoch 3/3
47/47 [==============================] - 59s 1s/step - loss: 0.0092 - accuracy: 0.9987 - val_loss: 0

In [6]:
from keras.models import load_model
model = load_model('model-best2')

In [20]:
hand_sign_images

array([[[[0.00784314],
         [0.00784314],
         [0.00784314],
         ...,
         [0.04313725],
         [0.04705882],
         [0.04705882]],

        [[0.00392157],
         [0.00784314],
         [0.00784314],
         ...,
         [0.04705882],
         [0.04705882],
         [0.04705882]],

        [[0.00392157],
         [0.00784314],
         [0.00392157],
         ...,
         [0.04705882],
         [0.04313725],
         [0.04705882]],

        ...,

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00784314],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]]],


       [[[0.20392157],
         [0.21960784],
         [0.21

In [ ]:
source = cv2.VideoCapture(0)
while 1:
    not_to_use, image = source.read()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    x = 30
    y = 30
    w = 350
    h = 350
    hand_roi = gray[y:y+w, x:x+h]
    resized_image = cv2.resize(hand_roi, (100, 100))
    normalized_image = resized_image/255
    reshaped_face = np.reshape(normalized_image, (1, 100, 100, 1))
    result = model.predict(reshaped_face)[0]
    print("Result : ",result)
    max_elem = max(list(result))   
    print("Max Prob : ",max_elem)
    index_of_max = list(result).index(max_elem)
    cv2.putText(image, sign_and_numbers[index_of_max], (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2)
    cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
    cv2.imshow('Verzeo Project', image)
    key = cv2.waitKey(1)
    if key == 27:
        break
cv2.destroyAllWindows()
source.release()